### ISSUE TITLE
When double clicking on node, use the main program as object

### ISSUE THREAD

**Issue by MDagni** [fidley/ADT-Classic-Outline-Frontend#10]
When the active editor displays an include program and double clicking on a node (such as a subroutine), it sends the include name to the RFC Z_ADTCO_GET_URI_FOR_TREE_NODE. This doesn't work if the subroutine is in another include.

It should send the main program name displayed on top of the tree.

Example: Display include DEMO_DYNPRO_MODIFY_SCREEN_SEL and double-click on subroutine 
![image](https://user-images.githubusercontent.com/33897441/157204300-341828f0-5616-4974-841a-420652de38bb.png)

Values sent:
NODE= 000037OPU ....
OBJECT_NAME= DEMO_DYNPRO_MODIFY_SCREEN_SEL
OBJECT_TYPE= REPS

This doesn't generate an URI.

If you can send these values:
NODE= 000037OPU ....
OBJECT_NAME= DEMO_DYNPRO_MODIFY_SCREEN
OBJECT_TYPE= PROG/P

It would generate the URI as /sap/bc/adt/programs/programs/demo_dynpro_modify_screen/source/main#start=139,5

**Comment by fidley** [comment]
#12
