### ISSUE TITLE
Objects are not sorted by name in the tree

### ISSUE THREAD

**Issue by MDagni** [fidley/ADT-Classic-Outline-Frontend#11]
Objects in the tree are not always sorted by name, but in the order of creation. They should always be sorted by name.

I created a new program and created subroutine bbb:
![image](https://user-images.githubusercontent.com/33897441/157214840-beb6dab5-d4d7-4064-ba77-5e0701114a41.png)

Then I created another subroutine aaa:
![image](https://user-images.githubusercontent.com/33897441/157214900-ef6b11ca-1518-4223-a744-3e4e198e3812.png)

The new subroutine is displayed at the bottom because WB_ANYTYPE_RETURN_OBJECT_LIST function returns objects in the order of creation.

**Comment by fidley** [comment]
I was always receiving it in good sequence so far. Cannot repeat it :(
Additionally I've added the call of the  WB_TREE_ACTUALIZE when you get tree for program or include, as I saw behaviour that the entries in the tree were not updated after changes. I had to manually rebuild object list in SE80 to get current state.

I will put it soon on the backend github so you can then test if this helps also at your system.

**Comment by fidley** [comment]
Please try again after updating to the latest backend version

**Comment by MDagni** [comment]
I have updated the backend and it works perfect 👍 Thank you.
