### ISSUE TITLE
Double click does not react when project name eq EHD_100

### ISSUE THREAD

**Issue by fidley** [fidley/ADT-Classic-Outline-Frontend#16]

**Comment by fidley** [comment]
@Ennowulff

**Comment by fidley** [comment]
This seems to be issue with the AdtNavigationServiceFactory.createNavigationService().navigateWithExternalLink(x,x) so standard ADT class
> eclipse.buildId=4.25.0.I20220831-1800
> java.version=19
> java.vendor=Oracle Corporation
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
> Framework arguments:  -product org.eclipse.platform.ide
> Command-line arguments:  -product org.eclipse.platform.ide -data C:\SAP\eclipse-workspace/../runtime-debug -dev file:C:/SAP/eclipse-workspace/.metadata/.plugins/org.eclipse.pde.core/debug/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog
> 
> This is a continuation of log file C:\SAP\runtime-debug\.metadata\.bak_0.log
> Created Time: 2022-10-26 12:43:12.677
> 
> com.sap.adt.logging
> Error
> Wed Oct 26 13:02:05 CEST 2022
> Error setting project context EHD.100 for URI adt://EHD_100/sap/bc/adt/oo/classes//aeb/cl_01_object/source/main#start=11,13
> 
> java.net.URISyntaxException: Illegal character in hostname at index 10: adt://EHD.100/sap/bc/adt/oo/classes//aeb/cl_01_object/source/main#start=11,13
> 	at java.base/java.net.URI$Parser.fail(URI.java:2970)
> 	at java.base/java.net.URI$Parser.parseHostname(URI.java:3509)
> 	at java.base/java.net.URI$Parser.parseServer(URI.java:3354)
> 	at java.base/java.net.URI$Parser.parseAuthority(URI.java:3273)
> 	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3215)
> 	at java.base/java.net.URI$Parser.parse(URI.java:3171)
> 	at java.base/java.net.URI.<init>(URI.java:705)
> 	at java.base/java.net.URI.<init>(URI.java:806)
> 	at com.sap.adt.tools.core.ui.internal.openurl.AdtFileStore.encodeExternalPath(AdtFileStore.java:192)
> 	at com.sap.adt.tools.core.ui.internal.navigation.NavigationService.navigateWithExternalLink(NavigationService.java:588)
> 	at com.abapblog.classicOutline.tree.TreeDoubleClickListener.doubleClick(TreeDoubleClickListener.java:54)
> 	at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:780)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
> 	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
> 	at org.eclipse.jface.viewers.StructuredViewer.fireDoubleClick(StructuredViewer.java:777)
> 	at org.eclipse.jface.viewers.AbstractTreeViewer.handleDoubleSelect(AbstractTreeViewer.java:1542)
> 	at org.eclipse.jface.viewers.StructuredViewer$4.widgetDefaultSelected(StructuredViewer.java:1211)
> 	at org.eclipse.jface.util.OpenStrategy.fireDefaultSelectionEvent(OpenStrategy.java:272)
> 	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:329)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
> 	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
> 	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

**Comment by fidley** [comment]
Error raised to SAP colleagues :-)

**Comment by Ennowulff** [comment]
Thanks for caring! ❤️

**Comment by fidley** [comment]
If project name ends with numbers, then somehow the underscore is replaced by SAP classed to dot. This makes troubles. There is other way to navigate to the object, but it behaves totally different, means the URIs needs to be prepared in different way. I've done some adaptations and for new releases it will use the navigation to ADT object instead of ADT external link. Anyway tests are needed.

For the old systems, the solution is to create project which does not end like _100, or _111 or whatever sequence of Underscore + Number.

**Comment by Ennowulff** [comment]
This is really a weird behaviour.
I would suggest to update the documentation that these kinds of project names cause trouble 😉
Maybe you can check at event "double click" if the project name is a troublemaker to give a hint to the user?

**Comment by fidley** [comment]
Could be an option

**Comment by fidley** [comment]
done with #21
