### ISSUE TITLE
Show method redefinitions in subclasses

### ISSUE THREAD

**Issue by fidley** [fidley/ADT-Classic-Outline-Frontend#17]
I have built a framework which uses massive inheritance. I have a superclass with a method for each userexit there is in SAPMV45A. you can define an exit class that will be called if active for the current organizational values. In the exit class you can redefine the methods for the userexits you need. That means there is for example a method USEREXIT_SAVE_DOCUMENT in the super class. An inherited exit class redefines only this method because this is the place where some customer logic is needed. Back to your plugin: It would be cool if you could display under a method all classes, that redefined this method. Here is a sample report that find’s out redefinition: https://blogs.sap.com/2018/06/26/find-redefinitions/
Class Zcl_userexits_Master
methods >
  - USEREXIT_UNUSED
  - USEREXIT_SAVE_DOCUMENT_PREPARE
     redefinitions >
       - class zcl_userexit_002
       - class zcl_userexit_004
       
       
 Adt feature request:

You are right, that this function should be called only on demand.
Maybe using the context menu?
Then you do not need a separate option.

My idea with the subsequent folder “redefinitions” might be not that good because then you will need to have a folder expander in front of any method name “>”. When you then click and see “redefinitions” and don’t see something… ☹

Otherwise: the folder expander might be only displayed if the current class has at least one inherited class. This should be determined quite fast.

 

I created this repository: https://github.com/Ennowulff/adt-classic-outline-example-redefinition
![image](https://user-images.githubusercontent.com/7912195/197870623-bfae864a-9986-4b18-8900-ff4bbb0f37d1.png)

@Ennowulff

**Comment by fidley** [comment]
I think I need some volunteers to do some test :D 
I've used cl_oo_class_relations as it gets superclasses, subclasses and all redefinitions at time.
![image](https://user-images.githubusercontent.com/7912195/201542842-94b78e4b-d3a1-4790-b0c6-dab756581e32.png)

I see also that after adding all levels of subclasses to the tree, in some cases it's slowing down the tree creation. For ex. CL_BSP_CONTROLLER shows 26K of subclasess. May be not necessary to show all of them from the scratch. I'd say show 50 and then load at demand?
![image](https://user-images.githubusercontent.com/7912195/201542937-2d24ded3-ff2c-4769-821d-cae28c05bb3a.png)

**Comment by Ennowulff** [comment]
I think 50 subclasses at once should be enough. 
More than 25000 subclasses should be an absolute exemption... 😅

**Comment by fidley** [comment]
True, but I need to think about solution for this, because this also interacts with the redefinition of the methods. I'd need to test what takes the most time here, probably tree creation, but I need to double check.

**Comment by Ennowulff** [comment]
Are you sure with the subclasses of CL_BSP_CONTROLLER??

In my system CL_BSP_CONTROLLER only has 16 subclasses.
Even sub-sub-classes are only 464...

**Comment by fidley** [comment]
We have more BSPs then. Subclasses will be shown also with sub-sub-sub-sub classes.

**Comment by Ennowulff** [comment]
wouldnÄt it make sense to only show direct sub classes?

**Comment by fidley** [comment]
Yes and no :-) Depends what is preferable by developer. It could be also done as setting in the preferences to give developer a chance to decide.

**Comment by MDagni** [comment]
I would prefer the default to be "direct sub classes only". Some classes will have many sub-sub classes (like cx_root), the other choice might cause a lot of delay.

**Comment by MDagni** [comment]
May be make the choice per-class? Like "I want this class to show all sub-sub classes". The plugin will have to remember this choice of course.

**Comment by Ennowulff** [comment]
I just checked the main reason for this issue... The task was to display not just all sub classes. Your plugin already does this perfectly. The idea was to display the sub classes that have redefined a specific method.

**Comment by fidley** [comment]
This is also included here :)

**Comment by Ennowulff** [comment]
Then I don't exactly understand what is hidden behind "sub classes" in this case...

**Comment by fidley** [comment]
Ok, seems I made some confusion. I though my last changes to add redefinition of methods, made also that sub-sub classes are visible, but seems it was already included in previous version.

Anyway I've added following preferences , for the moment globally 

![image](https://user-images.githubusercontent.com/7912195/201728607-a2acf2c9-b821-46e3-8e9f-2c0bc4a99f90.png)

In default both will be disabled, but you need backend to be updated in order this works correclty

Beta version available now: 
1. Frontent update site : https://fidley.github.io/ADTPluginsUpdateSiteBeta/UpdateSite/
2. Backend update from this branch https://github.com/fidley/ADT-Classic-Outline-Backend/tree/RedefinitionsItemCounterURICall

**Comment by MDagni** [comment]
I like this new version, it works very well 👍

![image](https://user-images.githubusercontent.com/33897441/201905688-07cf13a3-a442-4331-a3b5-e0c22e1f10c1.png)

Overlay icons appear too.

I'll leave the settings like this:

![image](https://user-images.githubusercontent.com/33897441/201905772-618a7d1f-81f3-46b5-92d0-544a6dca5e8a.png)

**Comment by MDagni** [comment]
Fetch redefinitions works for multiple sub-levels even if you don't choose "load all levels of subclasses".

![image](https://user-images.githubusercontent.com/33897441/201906577-ec02e7ac-7bc5-42c8-8be5-2e1cd1a953ed.png)

**Comment by MDagni** [comment]
I just noticed that the counter in the "Methods (1)" heading shows the number one less than actual; it should say "Methods (2)".

**Comment by fidley** [comment]
> Fetch redefinitions works for multiple sub-levels even if you don't choose "load all levels of subclasses".
> 
> ![image](https://user-images.githubusercontent.com/33897441/201906577-ec02e7ac-7bc5-42c8-8be5-2e1cd1a953ed.png)

Ok, I've corrected that, will update github soon.

**Comment by fidley** [comment]
> I just noticed that the counter in the "Methods (1)" heading shows the number one less than actual; it should say "Methods (2)".

Also found the issue :)

**Comment by fidley** [comment]
> > Fetch redefinitions works for multiple sub-levels even if you don't choose "load all levels of subclasses".
> > ![image](https://user-images.githubusercontent.com/33897441/201906577-ec02e7ac-7bc5-42c8-8be5-2e1cd1a953ed.png)
> 
> Ok, I've corrected that, will update github soon.

backend component corrected and uploaded to github

**Comment by MDagni** [comment]
> > Fetch redefinitions works for multiple sub-levels even if you don't choose "load all levels of subclasses".
> > ![image](https://user-images.githubusercontent.com/33897441/201906577-ec02e7ac-7bc5-42c8-8be5-2e1cd1a953ed.png)
> 
> Ok, I've corrected that, will update github soon.

Why did you change that, I had liked it that way 😅

**Comment by fidley** [comment]
> Why did you change that, I had liked it that way 😅

New parameter?

**Comment by MDagni** [comment]
Sounds good to me.

**Comment by fidley** [comment]
please update both backend and frontend again. New parameter and some refactoring done. #16 should be also solve with it.

**Comment by Ennowulff** [comment]
Works like charm ❤️👍

**Comment by Ennowulff** [comment]
One comment: the redefinitions are perfect, but: 
IMHO it is not obvious that these are redefinitions. maybe it was clearer, if you added a comment to the number of redefinitions?
like:
 ... method_abc (4 redefinitions)
 ... method_xyz (2 redefinitions)

What do you think?

**Comment by fidley** [comment]
Initially I was thinking about hierarchy"
---method
----redefinitions
----classs1
----class 2
but then this one level of folder is unnecessary and causes one more click always to expand ;)

I will see if I can easily adapt the counter to display it as you want, but then we loose the visibility of the mehtod name (if it is in dictionary)

**Comment by fidley** [comment]
maybe some abbreviations?

**Comment by Ennowulff** [comment]
Maybe just a documentation/ learning issue... 😄 
Or is it possible to show a quickinfo when hovering over (number)?

**Comment by fidley** [comment]
You mean this?
![image](https://user-images.githubusercontent.com/7912195/202233671-85b9f139-26b2-44e0-bf8c-8777edd69ed7.png)

**Comment by Ennowulff** [comment]
exactly 😆

**Comment by fidley** [comment]
done wiith #21
